# Clippy configuration for strict linting
msrv = "1.70"
allow-dirty = false
allow-staged = false
allow-partial-results = false

[dms]
# Disallowed methods - prevent unsafe patterns
disallowed-methods = []

[lints]
# The lint groups we want to enable
all = "warn"
correctness = "deny"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"

# Specific lints we want to deny
clippy::all = "warn"
clippy::pedantic = "warn"
clippy::nursery = "warn"
clippy::cargo = "warn"
clippy::correctness = "deny"
clippy::suspicious = "warn"
clippy::complexity = "warn"
clippy::perf = "warn"
clippy::style = "warn"

# Allow some pedantic lints that are too strict
clippy::module_name_repetitions = "allow"
clippy::must_use_candidate = "allow"
clippy::return_self_not_must_use = "allow"
clippy::missing_errors_doc = "allow"
clippy::missing_panics_doc = "allow"
clippy::unnecessary_wraps = "allow"

# Allow some nursery lints that may be too experimental
clippy::empty_line_after_doc_comments = "allow"
clippy::iter_with_drain = "allow"
clippy::needless_collect = "allow"
clippy::non_send_fields_in_send_ty = "allow"
clippy::redundant_pub_crate = "allow"
clippy::significant_drop_tightening = "allow"