# Rust formatting configuration for AI development
edition = "2021"
max_width = 160  # Increased for better AI-generated code readability
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_arm_leading_pipes = "Never"
match_arm_blocks = false
match_block_trailing_comma = false
combine_control_expr = true
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
comment_width = 120  # Increased to match max_width scaling
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_generated_files = false
skip_children = false
unstable_features = false