# Rust formatting configuration for production development
edition = "2021"
max_width = 160  # Increased for better readability with long function signatures
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_arm_leading_pipes = "Never"
match_arm_blocks = false
match_block_trailing_comma = false
combine_control_expr = true
group_imports = "StdExternalCrate"
format_generated_files = false
skip_children = false
# Note: The following configurations require nightly Rust and are disabled for stable builds:
# comment_width = 120
# normalize_comments = false 
# normalize_doc_attributes = false
# imports_indent = "Block"
# imports_layout = "Mixed"
# imports_granularity = "Crate"